/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.view;

/**
 *
 * @author Admin
 */
public class AboutJDialog extends javax.swing.JDialog {

    /**
     * Creates new form About
     */
    public AboutJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGioiThieu = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CÔNG TY NƯỚC GIẢI KHÁT TIENLONG");

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/images/logo_1.png"))); // NOI18N
        lblTitle.setMaximumSize(new java.awt.Dimension(512, 331));
        lblTitle.setMinimumSize(new java.awt.Dimension(512, 331));
        lblTitle.setPreferredSize(new java.awt.Dimension(512, 331));
        getContentPane().add(lblTitle, java.awt.BorderLayout.CENTER);

        txtGioiThieu.setEditable(false);
        txtGioiThieu.setText("Đây là phần mềm cung cấp giải pháp cho doanh nghiệp TIENLONG. Phần mềm giúp giảm\ntải nhanh chóng các công việc thủ công dẫn dễ đến sai xót từ khâu bán hàng đến khâu\nchiết rót, kiểm tra …, giúp người bán hàng nhanh và thuận tiện hơn, giúp các lãnh đạo\ncó thể quản lý một cách hiệu quả.\n\nPhần mềm ngoài các chức năng cập nhật thông tin, phân quyền người sử dụng, sao lưu\nvà phục hồi cơ sở dữ liệu, quản lý phòng ban, nhân viên, quản lý các loại bia và nước\ngiải khát, quản lý các dụng cụ chứa… Phần mềm còn có thể xuất các báo cáo để in hay\ndưới dạng word, excel, pdf.. theo từng loại hàng hóa, từng nhân viên, theo doanh thu…\n\nPhần mềm còn hướng tới tiêu chí gần gũi và thân thiện hơn với người sử dụng để giúp\nngười sử dụng có thể sử dụng phần mềm một cách nhanh chóng và đầy hiệu quả.\n\nPhần mềm có thể tùy biến theo các yêu cầu mới của khách hàng."); // NOI18N
        txtGioiThieu.setMinimumSize(new java.awt.Dimension(43, 118));
        jScrollPane1.setViewportView(txtGioiThieu);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutJDialog dialog = new AboutJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextPane txtGioiThieu;
    // End of variables declaration//GEN-END:variables
}
